@import url('https://fonts.googleapis.com/css2?family=Fraunces:opsz,wght@9..144,400;9..144,500;9..144,600;9..144,700&family=Noto+Sans:wght@400;500;600;700&family=Noto+Sans+Arabic:wght@400;500;600;700&family=Noto+Sans+SC:wght@400;500;600;700&display=swap');

:root{
  --bg:#f6f3ea;--bg-soft:#efeadd;--surface:#fff;--surface-2:#fbf9f2;
  --text:#1b2430;--text-soft:#4a5361;--border:rgba(27,36,48,.12);
  --gold:#9c7530;--gold-light:#c9a15a;--gold-soft:rgba(156,117,48,.14);
  --dark:#171316;--dark-2:#211b1e;--danger:#a33b35;
  --font-display:'Fraunces','Noto Serif',serif;--font-body:'Noto Sans','Noto Sans Arabic','Noto Sans SC',sans-serif;
  --radius:14px;--shadow:0 14px 40px rgba(27,36,48,.11);--ease:cubic-bezier(.22,.9,.32,1);
}
body[data-theme="dark"]{--bg:#10151c;--bg-soft:#161d27;--surface:#1a222e;--surface-2:#1e2733;--text:#ede8dc;--text-soft:#b7bec9;--border:rgba(237,232,220,.13);--gold:#c9a15a;--gold-light:#e0bc7c;--gold-soft:rgba(201,161,90,.16);--dark:#0d0f13;--dark-2:#171b22;--shadow:0 20px 60px rgba(0,0,0,.4)}
*{box-sizing:border-box}html{scroll-behavior:smooth}body{margin:0;background:var(--bg);color:var(--text);font-family:var(--font-body);font-size:16px;line-height:1.6;-webkit-font-smoothing:antialiased;transition:.3s background,.3s color}html[dir="rtl"] body{direction:rtl}img,svg{display:block;max-width:100%}a{color:inherit;text-decoration:none}button,input,textarea,select{font:inherit}button{cursor:pointer}button:disabled{opacity:.6;cursor:not-allowed}ul{margin:0;padding:0;list-style:none}h1,h2,h3,h4{font-family:var(--font-display);font-weight:600;letter-spacing:-.01em}.container{width:min(1180px,100%);margin:auto;padding:0 28px}.eyebrow{font-size:11px;letter-spacing:.14em;text-transform:uppercase;color:var(--gold);font-weight:700}

.site-header{position:sticky;top:0;z-index:100;background:color-mix(in srgb,var(--bg) 92%,transparent);backdrop-filter:blur(14px);border-bottom:1px solid var(--border)}
.nav{min-height:72px;display:flex;align-items:center;gap:22px}.brand{display:flex;align-items:center;gap:10px;font-weight:700;white-space:nowrap}.brand img{width:34px;height:34px}.brand-name{font-family:var(--font-display);font-size:22px}.nav-links{display:flex;align-items:center;justify-content:center;gap:22px;flex:1}.nav-links a{font-size:14px;color:var(--text-soft);padding:8px 2px;border-bottom:2px solid transparent}.nav-links a:hover,.nav-links a.active{color:var(--text);border-color:var(--gold)}.nav-actions{display:flex;align-items:center;gap:8px}.lang-select,.icon-btn,.menu-toggle{border:1px solid var(--border);background:var(--surface);color:var(--text);border-radius:8px;height:40px}.lang-select{padding:0 8px}.icon-btn,.menu-toggle{width:40px}.menu-toggle{display:none}

.btn{display:inline-flex;align-items:center;justify-content:center;min-height:42px;padding:10px 17px;border-radius:9px;border:1px solid transparent;font-weight:700;font-size:14px;transition:.2s transform,.2s background,.2s border-color}.btn:hover{transform:translateY(-1px)}.btn-primary{background:var(--gold);color:#fff;border-color:var(--gold)}.btn-primary:hover{background:var(--gold-light);border-color:var(--gold-light)}.btn-ghost{background:transparent;border-color:var(--border);color:var(--text)}

.hero{padding:115px 0 90px;text-align:center;background:radial-gradient(ellipse 800px 430px at 50% -5%,var(--gold-soft),transparent 65%)}.hero-logo{width:72px;height:72px;margin:0 auto 24px}.hero h1{max-width:850px;margin:10px auto 18px;font-size:clamp(38px,6vw,66px);line-height:1.05}.hero h1 em{color:var(--gold);font-style:italic}.hero-sub{max-width:720px;margin:0 auto 30px;color:var(--text-soft);font-size:18px}.hero-actions{display:flex;justify-content:center;gap:12px;flex-wrap:wrap}.hero-note{margin:22px auto 0;color:var(--text-soft);font-size:13px}

section{padding:88px 0}.section-head{max-width:720px;margin:0 auto 42px;text-align:center}.section-head h2{font-size:clamp(28px,4vw,42px);margin:8px 0 12px}.section-head p:not(.eyebrow){color:var(--text-soft)}
.features-grid,.artists-grid,.gallery-grid,.footer-grid{display:grid;gap:20px}.features-grid{grid-template-columns:repeat(4,1fr)}.feature-card{background:var(--surface);border:1px solid var(--border);border-radius:var(--radius);padding:26px;box-shadow:0 4px 16px rgba(0,0,0,.03)}.feature-card:hover{box-shadow:var(--shadow)}.feature-icon{width:48px;height:48px;display:grid;place-items:center;border-radius:50%;background:var(--gold-soft);color:var(--gold);font-weight:800;margin-bottom:16px}.feature-card h3{margin:0 0 8px;font-size:21px}.feature-card p{margin:0;color:var(--text-soft)}

.gallery-grid{grid-template-columns:repeat(4,1fr)}.frame{min-height:230px;position:relative;border-radius:var(--radius);overflow:hidden;border:1px solid var(--border);background:var(--surface);box-shadow:var(--shadow)}.frame-fill{height:100%;min-height:230px;background:linear-gradient(135deg,var(--gold-soft),var(--surface-2),rgba(122,46,46,.13))}.frame-label{position:absolute;left:14px;right:14px;bottom:12px;padding:7px 10px;border-radius:7px;background:rgba(15,15,15,.72);color:#fff;font-size:12px}.artwork-card{overflow:hidden;background:var(--surface);border:1px solid var(--border);border-radius:var(--radius);box-shadow:var(--shadow)}.artwork-card img{width:100%;height:220px;object-fit:cover}.artwork-info{padding:18px}.artwork-info h3{margin:0 0 4px}.artwork-info p{margin:0 0 10px;color:var(--text-soft)}.artwork-info strong{display:block;margin-bottom:12px;color:var(--gold)}

.artists-grid{grid-template-columns:repeat(4,1fr)}.artist-card{display:flex;align-items:center;gap:16px;background:var(--surface);border:1px solid var(--border);border-radius:var(--radius);padding:20px}.artist-avatar{width:58px;height:58px;flex:0 0 58px;border-radius:50%;border:1px solid var(--gold);background:linear-gradient(135deg,var(--gold-soft),transparent)}.artist-card h3{margin:0 0 3px;font-size:18px}.artist-card span{color:var(--gold);font-size:13px}.artist-card p{margin:0;color:var(--text-soft);font-size:14px}

.payment-panel{display:grid;grid-template-columns:1.25fr .75fr;gap:30px;align-items:center;background:var(--dark);color:#f3ece2;border-radius:22px;padding:52px}.payment-panel h2{font-size:clamp(28px,4vw,44px);margin:8px 0 14px}.payment-panel p{color:rgba(243,236,226,.76)}.token-list{margin-top:20px}.token-list li{margin:10px 0}.token-dot{display:inline-block;width:9px;height:9px;border-radius:50%;background:var(--gold-light);margin-right:8px}.payment-card{background:var(--dark-2);border:1px solid rgba(255,255,255,.12);border-radius:16px;padding:28px}.payment-card h3{font-size:26px;margin:8px 0 4px}.payment-card .btn{width:100%;margin-top:18px}

#about .section-head{max-width:850px}.contact-form{max-width:560px;margin:auto}.contact-form input,.contact-form textarea,#contactForm input,#contactForm textarea{width:100%;padding:12px;border-radius:8px;border:1px solid var(--border);background:var(--bg);color:var(--text);outline:none}.contact-form input:focus,.contact-form textarea:focus,#contactForm input:focus,#contactForm textarea:focus{border-color:var(--gold)}

.site-footer{background:var(--dark);color:#f3ece2;padding:60px 0 25px}.footer-grid{grid-template-columns:2fr repeat(3,1fr)}.site-footer p,.site-footer li{color:rgba(243,236,226,.7)}.site-footer h4{margin:0 0 12px}.site-footer li{margin:8px 0}.site-footer a:hover{color:#fff}.footer-bottom{display:flex;justify-content:space-between;gap:15px;border-top:1px solid rgba(255,255,255,.12);margin-top:40px;padding-top:18px;color:rgba(243,236,226,.6);font-size:12px}

.modal-overlay{position:fixed;inset:0;z-index:1000;display:none;place-items:center;background:rgba(0,0,0,.62);padding:20px}.modal-overlay.open{display:grid}.modal{position:relative;width:min(470px,100%);background:var(--surface);color:var(--text);border:1px solid var(--border);border-radius:18px;padding:32px;box-shadow:0 25px 80px rgba(0,0,0,.35)}.modal h3{font-size:28px;margin:0 0 10px}.modal p{color:var(--text-soft)}.modal .btn{width:100%;margin-top:12px}.modal-close{position:absolute;right:14px;top:10px;border:0;background:transparent;color:var(--text);font-size:30px;line-height:1}.reveal{opacity:0;transform:translateY(18px);transition:opacity .55s var(--ease),transform .55s var(--ease)}.reveal.in{opacity:1;transform:none}

@media(max-width:1000px){.features-grid,.artists-grid{grid-template-columns:repeat(2,1fr)}.gallery-grid{grid-template-columns:repeat(2,1fr)}.nav-links{gap:12px}.payment-panel{grid-template-columns:1fr}.footer-grid{grid-template-columns:1fr 1fr}}
@media(max-width:760px){.nav{min-height:64px}.nav-links{position:fixed;top:64px;left:0;right:0;bottom:0;display:flex;flex-direction:column;align-items:flex-start;justify-content:flex-start;gap:18px;padding:28px;background:var(--bg);transform:translateX(-110%);transition:transform .3s var(--ease);z-index:99}.nav-links.open{transform:translateX(0)}html[dir="rtl"] .nav-links{transform:translateX(110%)}html[dir="rtl"] .nav-links.open{transform:translateX(0)}.menu-toggle{display:block}.nav-actions .btn-primary{display:none}.hero{padding:90px 0 70px}.hero-sub{font-size:16px}.features-grid,.artists-grid,.gallery-grid{grid-template-columns:1fr}.payment-panel{padding:32px 24px}.footer-grid{grid-template-columns:1fr}.footer-bottom{flex-direction:column}.container{padding:0 18px}}
@media(prefers-reduced-motion:reduce){*,*::before,*::after{transition:none!important;scroll-behavior:auto!important}}
